name: CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Pin Node and enable Corepack
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Install PNPM based on the "packageManager" field in package.json
      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - run: pnpm install --frozen-lockfile=false
      - run: pnpm -w build

